### PR TITLE
Added script to automate the downloading of new package updates

### PR DESCRIPTION
**Pull request by SuperITMan**
The routine to execute the script is done thanks to Travis CI.
The script executes "git push" at the end **only** if the build is executed with a **cron** in Travis.

The variable **GH_TOKEN** has to be set in Travis to be able to push on GitHub.

To be able to use properly, you have to:
  - enable _Travis_ for the repository
  - set the variable **GH_TOKEN** in the plan settings on Travis with a GitHub token allowed to push on your repo
  - set a **cron** job on Travis to execute this every day and ensure all the packages are up to date all the time 😊 

Unfortunately, the logic for AuroreStore and AuroraServices is not yet implemented.
But I'm pretty sure it should doable 😊 

What do you think?

### CODE REVIEW

**Comment by SuperITMan** [comment]
Please don't pay attention to this nlw. I had some troubles when I tried to create a Pull Request on my repo. Sorry 🙏

**Comment by SuperITMan** [comment]
@qwow5 could you please apply the following steps to enable the auto-update feature ? :blush: 
  - enable Travis for the repository
  - set the variable **GH_TOKEN** in the plan settings on Travis with a GitHub token allowed to push on your repo
  - set a **cron** job on Travis to execute this every day and ensure all the packages are up to date all the time blush

**Comment by qwow5** [comment]
I enabled Travis and set a cron job. I could not find the GH_TOKEN variable in settings.

**Comment by SuperITMan** [comment]
You have to add the variable yourself:
image

**Comment by qwow5** [comment]
Ok, everything is good to go.

**Pull request merged**
